DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS path_entry;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_name TEXT NOT NULL,
    first_name TEXT NOT NULL,
    mail TEXT NOT NULL
);

CREATE TABLE path_entry (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type TEXT NOT NULL,
    who TEXT NOT NULL,
    activity TEXT NOT NULL,
    note TEXT NOT NULL,
    created_by INTEGER DEFAULT 0
);